import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    default: "Akira",
    template: "%s | Akira",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <div style={{ padding: "1rem", backgroundColor: "red" }}>
          <p>Root layout</p>
          <div style={{ backgroundColor: "white" }}>{children}</div>
        </div>
      </body>
    </html>
  );
}
